spring.application.name=MyBank


#MSSQL DATABASE CONFIGURATION
spring.datasource.url =dbc:sqlserver://localhost:1433;databaseName=MyBank;encrypt=true;trustServerCertificate=true

#Database credentials
spring.datasource.username = Kindy
spring.datasource.password =123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#=========================================
#JPA / HIBERNATE CONFIGURATION
#=========================================
# 'UPDATE' AUTOMATICALLY CREATES/UPADATES TABLE BASED ON  THE JAVA ENTITIES
spring.jpa.hibernate.ddl-auto=update

#Show generated SQL queries in the console for debugging
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

#Specify the SQL Server dialect
spring.jpa.database-platform = org.hibernate.dialect.SQLServerDialect

# ==========================================
# MULTITHREADING GESTION (CONNECTION POOL)
# ==========================================
# HikariCP manages simultaneous connections to the DB
# Defines the maximum number of concurrent connections
spring.datasource.hikari.maximum-pool-size=10
